changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feat
        - refactor
    - title: 🐛 Bug Fixes
      labels:
          - fix
    - title: 👒 Dependencies
      labels:
        - dependencies
