name: advanced_grouped_list
description: A ScrollablePositionedList where the list items can be grouped into sections.
version: 1.0.0
homepage: https://github.com/andreystavitsky/advanced_grouped_list
repository: https://github.com/andreystavitsky/advanced_grouped_list

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.3 <=5.0.0"